version: '3'

volumes:
  kami-discovery-node-modules:


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kami-discovery
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
      - kami-discovery-node-modules:/app/node_modules
    ports:
      - 5173:5173
